query PokemonQuery {
  pokemon_v2_pokemonsprites {
    id
    sprites
    pokemon_v2_pokemon {
      name
      id
      weight
      base_experience
      height
      pokemon_v2_pokemonabilities {
        pokemon_v2_ability {
          name
        }
      }
    }
  }
}
